import { ArrowRight, ArrowUpRight, Check } from "lucide-react";
import { Link } from "wouter";
import MarketingLayout from "@/components/MarketingLayout";
import SEO from "@/components/SEO";

const principles = ["Understand the business before choosing the implementation", "Keep communication direct and decisions documented", "Design for the people operating the product after launch", "Treat security, performance, and maintainability as delivery requirements"];

export default function AboutPage() {
  return <MarketingLayout>
    <SEO title="About Malek Fouda | Full-Stack Developer" description="Meet Malek Fouda, a Cairo-based full-stack developer delivering e-commerce platforms, business systems, integrations, and white-label development." canonicalPath="/about" />
    <header className="marketing-hero"><div className="marketing-shell grid gap-10 lg:grid-cols-[1fr_0.45fr] lg:items-end"><div><p className="marketing-eyebrow">About Malek</p><h1 className="marketing-title">A developer who cares about <span className="gradient-text">what happens after launch.</span></h1></div><p className="text-lg leading-8 text-gray-300">I build software for real businesses—where reliability, clear communication, and maintainable decisions matter as much as the interface.</p></div></header>
    <section className="border-y border-gray-800 bg-gray-950/70"><div className="marketing-shell marketing-section grid gap-10 lg:grid-cols-2"><div className="marketing-card p-7 sm:p-9"><h2 className="text-3xl font-bold">Based in Cairo, working internationally.</h2><p className="mt-5 leading-8 text-gray-400">My work spans e-commerce, learning platforms, logistics, dashboards, portals, and integrations. I work directly with growing businesses and founders, and discreetly with agencies that need dependable development capacity.</p><p className="mt-5 leading-8 text-gray-400">I am most useful when the requirements are complicated but the final experience needs to feel straightforward.</p></div><div className="marketing-card p-7 sm:p-9"><p className="marketing-eyebrow">Working principles</p><ul className="mt-6 space-y-5">{principles.map((principle) => <li key={principle} className="flex gap-3 leading-7 text-gray-300"><Check className="mt-1 h-5 w-5 shrink-0 text-green-400" />{principle}</li>)}</ul></div></div></section>
    <section className="marketing-section"><div className="marketing-shell"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Commerce", "Shopify, WordPress, WooCommerce, payments, shipping, and storefront integrations."], ["Applications", "React, Node.js, PHP, Laravel, dashboards, portals, and authenticated workflows."], ["Operations", "APIs, automation, role-based access, reporting, deployment, and maintenance."], ["Partnerships", "Direct delivery for businesses and white-label implementation for agencies."]].map(([title, copy]) => <article key={title} className="marketing-card p-6"><h2 className="text-xl font-bold text-green-400">{title}</h2><p className="mt-4 leading-7 text-gray-400">{copy}</p></article>)}</div><div className="mt-12 flex flex-wrap justify-center gap-4"><Link href="/contact" className="primary-cta">Send Project Details <ArrowRight className="h-4 w-4" /></Link><a href="https://calendly.com/malekfouda2000/30min" target="_blank" rel="noopener noreferrer" className="secondary-cta">Book a Call <ArrowUpRight className="h-4 w-4" /></a></div></div></section>
  </MarketingLayout>;
}
