import type { InsertCaseStudy } from "@shared/schema";

export const AIQDA_CASE_STUDY: InsertCaseStudy = {
  projectId: null,
  slug: "aiqda-learning-platform",
  title: "Aiqda — From Learning MVP to Operational Platform",
  clientName: "Aiqda",
  industry: "Education Technology / Creative Services",
  summary: "A full-stack platform that brings acquisition, subscription learning, creator and studio onboarding, consultations, payments, finance, and analytics into one operational system.",
  context: "Aiqda began as a skills-learning product for members and creators. As the commercial model matured, the product needed to support more than content delivery: public acquisition, paid subscriptions, creator and studio intake, consultation bookings, financial administration, and reliable reporting all had to work together.\n\nThe product language was also evolving. Customer-facing terms such as chapters, content, creators, members, and achievements needed to change without destabilizing the established backend models.",
  problem: "A conventional course catalogue could not support Aiqda’s operating model. Visitors needed to understand the offer before creating an account. Members needed immediate, entitlement-based access after payment. Creators and studios required different review and onboarding paths. Administrators needed one place to manage users, content, subscriptions, payments, finance, applications, consultations, and analytics.\n\nThe largest technical risk sat at the boundaries between these areas: payment confirmation and access, viewing progress and qualification, refunds and subscription state, or internal activity and customer analytics.",
  role: "Full-stack product development across the React/Vite frontend, Express/Mongoose backend, payment and video integrations, role-based experiences, operational dashboards, analytics, and production delivery.",
  approach: "The platform was treated as one connected operating system rather than a collection of pages. Public discovery remained accessible before login. Member, creator, and administrator capabilities were separated through role and ownership checks. Existing backend terminology stayed stable while the interface adopted Aiqda’s customer-facing language.\n\nCommercial workflows were designed around dependable state changes. Tap webhooks and verified charges drive subscription activation; finance uses integer minor units and basis points; Vimeo activity feeds learning progress; and staff activity is excluded from customer analytics and compensation signals.",
  solution: "The resulting MERN application connects the public website to three role-specific product experiences. Members can subscribe, access eligible chapters, watch Vimeo content, complete quizzes, track progress, manage billing, and book consultations. Creators move from application and approval into controlled content management. Administrators oversee users, content, applications, consultations, subscriptions, payments, refunds, finance, analytics, and platform settings from a centralized dashboard.\n\nTap checkout, saved payment references, webhook synchronization, and refund handling replace manual subscription proof workflows. The finance layer supports deterministic allocation and payout planning, while internal analytics covers acquisition, engagement, commerce, and learning without counting administrator or creator review activity as customer behavior.",
  challenges: [
    "Keeping payment, subscription, refund, and content-access states consistent across redirects and webhooks.",
    "Supporting distinct member, creator, studio, and administrator workflows without duplicating the product architecture.",
    "Calculating watch progress, qualification, chapter completion, rewards, and finance signals without contamination from internal review activity.",
    "Changing product terminology throughout the interface while preserving stable database and API contracts.",
    "Giving administrators dense operational control without adding friction to public discovery and member learning.",
  ],
  results: [
    "Replaced manual subscription proof review with electronic checkout and payment-confirmed activation.",
    "Unified customer acquisition, paid learning, applications, consultations, and administration in one product.",
    "Created dedicated member, creator, and administrator experiences with role and ownership enforcement.",
    "Established deterministic finance calculations for allocation, refunds, creator earnings, and payout planning.",
    "Separated customer analytics from administrator and creator activity for more reliable commercial reporting.",
  ],
  technologies: [
    "React",
    "TypeScript",
    "Vite",
    "Node.js",
    "Express",
    "MongoDB",
    "Mongoose",
    "Tap Payments",
    "Vimeo API",
    "Tailwind CSS",
    "Zustand",
    "Framer Motion",
  ],
  image: "/uploads/aiqda-case-study/01-home.webp",
  screenshots: [
    "/uploads/aiqda-case-study/01-home.webp",
    "/uploads/aiqda-case-study/01b-home-packages.webp",
    "/uploads/aiqda-case-study/02-chapters.webp",
    "/uploads/aiqda-case-study/09-member-dashboard.webp",
    "/uploads/aiqda-case-study/10-member-progress.webp",
    "/uploads/aiqda-case-study/11-member-subscription.webp",
    "/uploads/aiqda-case-study/12-member-payments.webp",
    "/uploads/aiqda-case-study/13-member-chapter-detail.webp",
    "/uploads/aiqda-case-study/14-member-content-progress.webp",
    "/uploads/aiqda-case-study/03-consultations.webp",
    "/uploads/aiqda-case-study/04-creator-application.webp",
    "/uploads/aiqda-case-study/05-studio-application.webp",
    "/uploads/aiqda-case-study/06-admin-dashboard.webp",
    "/uploads/aiqda-case-study/07-admin-analytics.webp",
    "/uploads/aiqda-case-study/08-admin-finance.webp",
  ],
  serviceSlugs: ["custom-business-systems", "maintenance-performance-security"],
  liveUrl: "https://aiqda.pro",
  isFeatured: true,
  isPublished: true,
  sortOrder: 2,
  seoTitle: "Aiqda Learning Platform Case Study | Malek Fouda",
  seoDescription: "How Aiqda evolved from a learning MVP into a full-stack platform for subscriptions, payments, video learning, creator operations, finance, and analytics.",
};

export const TABLIYA_CASE_STUDY: InsertCaseStudy = {
  projectId: null,
  slug: "tabliya-shopify-middleware",
  title: "Tabliya — Shopify Order Middleware Built for Recovery",
  clientName: "Tabliya",
  industry: "Food Production / E-commerce Operations",
  summary: "A production-oriented integration service that turns Shopify order events into traceable Tabliya operations, with mapping controls, idempotency, retries, replay, and manual review built into the workflow.",
  context: "Tabliya uses Shopify for online ordering and a separate operational platform for products, orders, payment methods, invoices, and production workflows. The two systems use different identifiers and data contracts, so transferring an order involves more than forwarding a webhook payload.\n\nThe integration needed to cover the complete order lifecycle while giving operators a practical way to understand and recover from failures without creating duplicate records.",
  problem: "A direct Shopify-to-API call would leave several operational risks unresolved. Shopify can redeliver webhooks, events can arrive close together, and Tabliya requires its own product IDs and payment-method values. Addresses, delivery dates, discounts, payment state, updates, and cancellations also need deliberate transformation.\n\nIf a product was not mapped or the destination API became unavailable, the system needed to preserve the event, stop an incomplete order from being created, explain the failure, and support a controlled retry after the underlying issue was fixed.",
  role: "Full-stack integration architecture and implementation across Shopify webhooks, payload transformation, PostgreSQL persistence, background processing, the Tabliya API client, admin tooling, observability, and deployment configuration.",
  approach: "The service was designed as an auditable event pipeline. Shopify webhook signatures are verified against the raw request body before an event is accepted. Valid events are stored before processing, deduplicated by webhook and Shopify order identifiers, and handed to BullMQ for retryable background work, with an in-process fallback when Redis is unavailable.\n\nProduct and payment mappings are maintained separately from order logic. The transformer resolves those mappings, normalizes customer and address data, calculates delivery dates, translates payment state, and refuses to create a partial destination order when a line item is unknown.",
  solution: "The TypeScript and Express service handles Shopify order creation, updates, payments, fulfillment changes, edits, and cancellations. It creates or updates the corresponding Tabliya order, stores both request and response context, and preserves the relationship between the two systems. Cancellation first uses a configured or detected Tabliya status, verifies the result, and falls back safely when required. Optional invoice synchronization is isolated behind configuration.\n\nA protected admin console exposes product and payment mappings, webhook events, synchronization logs, settings, unresolved exceptions, manual replay, and reconciliation tools. Operators can correct a mapping and retry the original event instead of rebuilding an order by hand or losing the audit trail.",
  challenges: [
    "Preventing duplicate Tabliya orders when Shopify redelivers the same event or an operator initiates a replay.",
    "Translating Shopify products, variants, payment labels, addresses, delivery dates, discounts, and payment states into Tabliya's API contract.",
    "Applying cancellation safely despite multiple possible destination status endpoints and preserving the cancellation reason and timestamp.",
    "Keeping webhook acknowledgement fast while supporting retries, reconciliation, and useful failure visibility.",
    "Blocking incomplete orders when a mapping is missing, then making recovery straightforward for an operator.",
  ],
  results: [
    "Established an idempotent order pipeline with stored raw events and explicit synchronization state.",
    "Covered order creation, updates, payment and fulfillment changes, edits, cancellations, and optional invoice follow-up.",
    "Created operator-managed product and payment mappings instead of relying on fragile title matching.",
    "Added retry, replay, reconciliation, structured logs, and a manual-review queue for recoverable failures.",
    "Verified the local build, health endpoint, protected admin access, invalid-signature rejection, and unmapped-product review path against an isolated PostgreSQL database.",
  ],
  technologies: [
    "Shopify Webhooks",
    "Node.js",
    "TypeScript",
    "Express",
    "PostgreSQL",
    "Drizzle ORM",
    "Redis",
    "BullMQ",
    "Axios",
    "Zod",
    "Pino",
  ],
  image: "/uploads/tabliya-case-study/01-integration-settings.png",
  screenshots: [
    "/uploads/tabliya-case-study/01-integration-settings.png",
    "/uploads/tabliya-case-study/02-webhook-events.png",
  ],
  serviceSlugs: ["shopify-development", "custom-business-systems", "maintenance-performance-security"],
  liveUrl: "https://github.com/malekfouda2/Shopify-Orders-Middleware",
  isFeatured: true,
  isPublished: true,
  sortOrder: 3,
  seoTitle: "Tabliya Shopify Middleware Case Study | Malek Fouda",
  seoDescription: "How a Shopify middleware service synchronizes Tabliya orders with secure webhooks, mappings, idempotency, retries, replay, logs, and manual review.",
};

export const DELIVERY_DATES_MANAGER_CASE_STUDY: InsertCaseStudy = {
  projectId: null,
  slug: "woocommerce-delivery-dates-manager",
  title: "Onirik — WooCommerce Delivery Scheduling Built Around Operations",
  clientName: "Onirik Pastry Boutique",
  industry: "Food & Beverage / E-commerce",
  summary: "A custom WooCommerce plugin that coordinates delivery zones, available dates, order capacity, cutoff times, same-day eligibility, pickup, and order records in one checkout workflow.",
  context: "Onirik Pastry Boutique needed checkout promises to reflect how orders are actually prepared and delivered across Cairo. Availability changes by delivery zone, weekday, order capacity, cutoff time, product eligibility, and blocked dates. Customers also need a separate pickup path from Heliopolis.\n\nThe solution had to feel native to WooCommerce while giving store operators control over these rules without editing code.",
  problem: "Standard WooCommerce shipping rates can price a destination, but they do not model the complete scheduling decision. A date that appears available in the browser may become invalid because the cutoff has passed, the day is blocked, capacity is full, or one product in the cart is not eligible for same-day fulfillment.\n\nDelivery and pickup also have different timing and fee behavior. Whichever path the customer chooses must be validated on the server and preserved through administration, customer order views, and email notifications.",
  role: "WooCommerce plugin architecture and implementation across checkout UX, shipping-zone rules, date availability, product eligibility, order metadata, administration, and High-Performance Order Storage compatibility.",
  approach: "WooCommerce shipping zones remain the source of destination structure, while the plugin adds an operational rules layer for allowed weekdays, cutoff times, same-day service, daily capacity, blocked dates, and flat fees. Product and variation settings determine whether every item in the cart can use same-day delivery or pickup.\n\nThe browser requests eligible dates through a nonce-protected AJAX endpoint, but checkout validation independently applies the same rules on the server. This keeps the interface responsive without trusting customer-submitted dates. Plugin settings are stored outside WordPress's autoloaded option set to reduce unnecessary memory pressure.",
  solution: "The plugin adds a clear delivery-or-pickup choice to checkout. Delivery customers select an enabled Cairo zone and then choose from dates that satisfy its calendar, cutoff, capacity, blocked-date, and cart-eligibility rules. The chosen zone sets the configured delivery fee. Pickup customers receive a dedicated Heliopolis message, pickup calendar, separate cutoff behavior, and no delivery charge.\n\nStore teams configure global and zone-specific rules from WooCommerce, set same-day eligibility per product or variation, and see the selected fulfillment method, zone, and date on orders. The same information flows into customer order details and transactional emails, with support for both legacy order storage and WooCommerce HPOS.",
  challenges: [
    "Keeping browser-side date choices and server-side checkout validation consistent across changing cart and zone conditions.",
    "Calculating same-day availability only when the cutoff has not passed and every cart item is eligible.",
    "Applying per-zone capacity and blocked dates without allowing an invalid or outdated date through checkout.",
    "Switching between delivery fees and zero-fee pickup while preserving a clear customer experience.",
    "Supporting WooCommerce's legacy order model and High-Performance Order Storage from the same plugin.",
  ],
  results: [
    "Created one checkout flow for zone-based delivery scheduling and Heliopolis pickup.",
    "Made delivery availability configurable by weekday, cutoff, same-day eligibility, capacity, and blocked date.",
    "Added server-side validation so unavailable dates cannot be accepted solely because they appeared in the browser.",
    "Carried fulfillment details into store administration, customer order views, and transactional emails.",
    "Verified PHP syntax, the installable archive, and plugin activation with WordPress and WooCommerce in an isolated local environment.",
  ],
  technologies: [
    "WordPress",
    "WooCommerce",
    "PHP",
    "JavaScript",
    "jQuery",
    "AJAX",
    "WooCommerce HPOS",
    "CSS",
  ],
  image: "/uploads/delivery-dates-manager/01-zone-delivery-checkout.webp",
  screenshots: [
    "/uploads/delivery-dates-manager/01-zone-delivery-checkout.webp",
    "/uploads/delivery-dates-manager/02-pickup-checkout.webp",
  ],
  serviceSlugs: ["wordpress-woocommerce", "custom-business-systems"],
  liveUrl: "https://github.com/malekfouda2/Delivery-Dates-Manager",
  isFeatured: true,
  isPublished: true,
  sortOrder: 4,
  seoTitle: "WooCommerce Delivery Scheduling Case Study | Malek Fouda",
  seoDescription: "A WooCommerce delivery scheduling plugin for zone rules, date capacity, cutoffs, same-day eligibility, Heliopolis pickup, and HPOS-ready orders.",
};

export const GIFTING_SYSTEM_CASE_STUDY: InsertCaseStudy = {
  projectId: null,
  slug: "woocommerce-gifting-system",
  title: "WooCommerce Gifting System — From Gift Checkout to Fulfillment",
  clientName: "WooCommerce Gifting System",
  industry: "E-commerce / Retail Operations",
  summary: "A custom WooCommerce plugin that captures gift details at checkout, issues a traceable single-use claim code, and alerts fulfillment when that code is used on a later order.",
  context: "The gifting workflow needed to connect two separate purchases. A customer first places an order for someone else and provides the recipient details. After that order progresses, the sender receives a code that can be used once on a future purchase to claim a physical gift.\n\nThis is an operational benefit rather than a price promotion. The code applies no discount; its purpose is to carry a reliable signal from the original gift order into the later fulfillment workflow.",
  problem: "A checkout note alone would not create a dependable process. Recipient details could be missed, repeated order-status events could create duplicate codes, and warehouse staff would have no structured way to recognize a later gift claim or trace it back to the source order.\n\nThe workflow also needed to fit WooCommerce's existing order and coupon models, expose useful information in administration, and remain compatible with both legacy order screens and High-Performance Order Storage.",
  role: "WooCommerce plugin architecture and implementation across classic checkout fields, validation, order metadata, coupon generation, HTML email notification, redemption tracking, administration, and HPOS compatibility.",
  approach: "The plugin is split into focused classes for checkout, persistence, coupon creation, notification, redemption, and administration. Gift fields appear only when the customer selects the gift option, while server-side checkout validation still requires the recipient name and phone before the order can proceed.\n\nWhen a gift order enters processing or completed status, the plugin first checks for an existing code. It then creates a WooCommerce coupon with a random order-linked identifier, zero discount, a single-use limit, a two-week expiry, and metadata pointing back to the source order. This uses WooCommerce's native order and coupon APIs rather than introducing a separate data store.",
  solution: "Customers can mark an order as a gift and provide a recipient name, phone number, and optional message directly in classic checkout. The information is saved on the order and presented in a distinct admin panel. Once the order progresses, the generated claim code is stored on the same order, added to its notes, and passed into a branded HTML email through WordPress mail.\n\nWhen that code is applied to a later order, the plugin records the code and original order ID on the new order. A green fulfillment alert tells staff to include the physical gift, while gift and redemption indicators make these orders easier to identify in WooCommerce lists.",
  challenges: [
    "Linking two separate WooCommerce orders without treating the claim code as a monetary discount.",
    "Preventing duplicate coupon creation when both processing and completed status hooks run for the same order.",
    "Keeping recipient details, generated-code metadata, order notes, and fulfillment alerts traceable across the workflow.",
    "Validating conditional checkout fields on the server while keeping the default purchase flow unchanged for non-gift orders.",
    "Supporting legacy WooCommerce order columns alongside HPOS order screens and APIs.",
  ],
  results: [
    "Created an end-to-end gift workflow from checkout capture through later-order fulfillment notification.",
    "Generated idempotent, zero-value, single-use claim codes with a two-week expiry and source-order metadata.",
    "Made gift details and redeemed-code relationships visible to store administrators without a separate dashboard.",
    "Kept the implementation inside native WooCommerce orders, coupons, hooks, and WordPress email delivery.",
    "Verified PHP syntax, archive integrity, plugin activation, checkout rendering, code generation, duplicate prevention, redemption tracking, and admin alerts in an isolated WordPress and WooCommerce environment.",
  ],
  technologies: [
    "WordPress",
    "WooCommerce",
    "PHP",
    "JavaScript",
    "jQuery",
    "WooCommerce Coupons",
    "HTML Email",
    "WooCommerce HPOS",
  ],
  image: "/uploads/gifting-system/01-gift-checkout.webp",
  screenshots: [
    "/uploads/gifting-system/01-gift-checkout.webp",
    "/uploads/gifting-system/02-gift-order-admin.webp",
    "/uploads/gifting-system/03-gift-claim-admin.webp",
  ],
  serviceSlugs: ["wordpress-woocommerce", "custom-business-systems"],
  liveUrl: "https://github.com/malekfouda2/Wordpress-Gifting-Plugin",
  isFeatured: true,
  isPublished: true,
  sortOrder: 5,
  seoTitle: "WooCommerce Gifting Plugin Case Study | Malek Fouda",
  seoDescription: "A WooCommerce gifting plugin for recipient details, single-use claim codes, HTML notifications, redemption tracking, and fulfillment alerts.",
};
