import type { InsertCaseStudy } from "@shared/schema";

export const AIQDA_CASE_STUDY: InsertCaseStudy = {
  projectId: null,
  slug: "aiqda-learning-platform",
  title: "Aiqda — From Learning MVP to Operational Platform",
  clientName: "Aiqda",
  industry: "Education Technology / Creative Services",
  summary: "A full-stack platform that brings acquisition, subscription learning, creator and studio onboarding, consultations, payments, finance, and analytics into one operational system.",
  context: "Aiqda began as a skills-learning product for members and creators. As the commercial model matured, the product needed to support more than content delivery: public acquisition, paid subscriptions, creator and studio intake, consultation bookings, financial administration, and reliable reporting all had to work together.\n\nThe product language was also evolving. Customer-facing terms such as chapters, content, creators, members, and achievements needed to change without destabilizing the established backend models.",
  problem: "A conventional course catalogue could not support Aiqda’s operating model. Visitors needed to understand the offer before creating an account. Members needed immediate, entitlement-based access after payment. Creators and studios required different review and onboarding paths. Administrators needed one place to manage users, content, subscriptions, payments, finance, applications, consultations, and analytics.\n\nThe largest technical risk sat at the boundaries between these areas: payment confirmation and access, viewing progress and qualification, refunds and subscription state, or internal activity and customer analytics.",
  role: "Full-stack product development across the React/Vite frontend, Express/Mongoose backend, payment and video integrations, role-based experiences, operational dashboards, analytics, and production delivery.",
  approach: "The platform was treated as one connected operating system rather than a collection of pages. Public discovery remained accessible before login. Member, creator, and administrator capabilities were separated through role and ownership checks. Existing backend terminology stayed stable while the interface adopted Aiqda’s customer-facing language.\n\nCommercial workflows were designed around dependable state changes. Tap webhooks and verified charges drive subscription activation; finance uses integer minor units and basis points; Vimeo activity feeds learning progress; and staff activity is excluded from customer analytics and compensation signals.",
  solution: "The resulting MERN application connects the public website to three role-specific product experiences. Members can subscribe, access eligible chapters, watch Vimeo content, complete quizzes, track progress, manage billing, and book consultations. Creators move from application and approval into controlled content management. Administrators oversee users, content, applications, consultations, subscriptions, payments, refunds, finance, analytics, and platform settings from a centralized dashboard.\n\nTap checkout, saved payment references, webhook synchronization, and refund handling replace manual subscription proof workflows. The finance layer supports deterministic allocation and payout planning, while internal analytics covers acquisition, engagement, commerce, and learning without counting administrator or creator review activity as customer behavior.",
  challenges: [
    "Keeping payment, subscription, refund, and content-access states consistent across redirects and webhooks.",
    "Supporting distinct member, creator, studio, and administrator workflows without duplicating the product architecture.",
    "Calculating watch progress, qualification, chapter completion, rewards, and finance signals without contamination from internal review activity.",
    "Changing product terminology throughout the interface while preserving stable database and API contracts.",
    "Giving administrators dense operational control without adding friction to public discovery and member learning.",
  ],
  results: [
    "Replaced manual subscription proof review with electronic checkout and payment-confirmed activation.",
    "Unified customer acquisition, paid learning, applications, consultations, and administration in one product.",
    "Created dedicated member, creator, and administrator experiences with role and ownership enforcement.",
    "Established deterministic finance calculations for allocation, refunds, creator earnings, and payout planning.",
    "Separated customer analytics from administrator and creator activity for more reliable commercial reporting.",
  ],
  technologies: [
    "React",
    "TypeScript",
    "Vite",
    "Node.js",
    "Express",
    "MongoDB",
    "Mongoose",
    "Tap Payments",
    "Vimeo API",
    "Tailwind CSS",
    "Zustand",
    "Framer Motion",
  ],
  image: "/uploads/aiqda-case-study/01-home.webp",
  screenshots: [
    "/uploads/aiqda-case-study/01-home.webp",
    "/uploads/aiqda-case-study/01b-home-packages.webp",
    "/uploads/aiqda-case-study/02-chapters.webp",
    "/uploads/aiqda-case-study/09-member-dashboard.webp",
    "/uploads/aiqda-case-study/10-member-progress.webp",
    "/uploads/aiqda-case-study/11-member-subscription.webp",
    "/uploads/aiqda-case-study/12-member-payments.webp",
    "/uploads/aiqda-case-study/13-member-chapter-detail.webp",
    "/uploads/aiqda-case-study/14-member-content-progress.webp",
    "/uploads/aiqda-case-study/03-consultations.webp",
    "/uploads/aiqda-case-study/04-creator-application.webp",
    "/uploads/aiqda-case-study/05-studio-application.webp",
    "/uploads/aiqda-case-study/06-admin-dashboard.webp",
    "/uploads/aiqda-case-study/07-admin-analytics.webp",
    "/uploads/aiqda-case-study/08-admin-finance.webp",
  ],
  serviceSlugs: ["custom-business-systems", "maintenance-performance-security"],
  liveUrl: "https://aiqda.pro",
  isFeatured: true,
  isPublished: true,
  sortOrder: 2,
  seoTitle: "Aiqda Learning Platform Case Study | Malek Fouda",
  seoDescription: "How Aiqda evolved from a learning MVP into a full-stack platform for subscriptions, payments, video learning, creator operations, finance, and analytics.",
};
