import type { InsertCaseStudy } from "@shared/schema";

export const AIQDA_CASE_STUDY: InsertCaseStudy = {
  projectId: null,
  slug: "aiqda-learning-platform",
  title: "Aiqda — From Learning MVP to Operational Platform",
  clientName: "Aiqda",
  industry: "Education Technology / Creative Services",
  summary: "A full-stack platform that brings acquisition, subscription learning, creator and studio onboarding, consultations, payments, finance, and analytics into one operational system.",
  context: "Aiqda began as a skills-learning product for members and creators. As the commercial model matured, the product needed to support more than content delivery: public acquisition, paid subscriptions, creator and studio intake, consultation bookings, financial administration, and reliable reporting all had to work together.\n\nThe product language was also evolving. Customer-facing terms such as chapters, content, creators, members, and achievements needed to change without destabilizing the established backend models.",
  problem: "A conventional course catalogue could not support Aiqda’s operating model. Visitors needed to understand the offer before creating an account. Members needed immediate, entitlement-based access after payment. Creators and studios required different review and onboarding paths. Administrators needed one place to manage users, content, subscriptions, payments, finance, applications, consultations, and analytics.\n\nThe largest technical risk sat at the boundaries between these areas: payment confirmation and access, viewing progress and qualification, refunds and subscription state, or internal activity and customer analytics.",
  role: "Full-stack product development across the React/Vite frontend, Express/Mongoose backend, payment and video integrations, role-based experiences, operational dashboards, analytics, and production delivery.",
  approach: "The platform was treated as one connected operating system rather than a collection of pages. Public discovery remained accessible before login. Member, creator, and administrator capabilities were separated through role and ownership checks. Existing backend terminology stayed stable while the interface adopted Aiqda’s customer-facing language.\n\nCommercial workflows were designed around dependable state changes. Tap webhooks and verified charges drive subscription activation; finance uses integer minor units and basis points; Vimeo activity feeds learning progress; and staff activity is excluded from customer analytics and compensation signals.",
  solution: "The resulting MERN application connects the public website to three role-specific product experiences. Members can subscribe, access eligible chapters, watch Vimeo content, complete quizzes, track progress, manage billing, and book consultations. Creators move from application and approval into controlled content management. Administrators oversee users, content, applications, consultations, subscriptions, payments, refunds, finance, analytics, and platform settings from a centralized dashboard.\n\nTap checkout, saved payment references, webhook synchronization, and refund handling replace manual subscription proof workflows. The finance layer supports deterministic allocation and payout planning, while internal analytics covers acquisition, engagement, commerce, and learning without counting administrator or creator review activity as customer behavior.",
  challenges: [
    "Keeping payment, subscription, refund, and content-access states consistent across redirects and webhooks.",
    "Supporting distinct member, creator, studio, and administrator workflows without duplicating the product architecture.",
    "Calculating watch progress, qualification, chapter completion, rewards, and finance signals without contamination from internal review activity.",
    "Changing product terminology throughout the interface while preserving stable database and API contracts.",
    "Giving administrators dense operational control without adding friction to public discovery and member learning.",
  ],
  results: [
    "Replaced manual subscription proof review with electronic checkout and payment-confirmed activation.",
    "Unified customer acquisition, paid learning, applications, consultations, and administration in one product.",
    "Created dedicated member, creator, and administrator experiences with role and ownership enforcement.",
    "Established deterministic finance calculations for allocation, refunds, creator earnings, and payout planning.",
    "Separated customer analytics from administrator and creator activity for more reliable commercial reporting.",
  ],
  technologies: [
    "React",
    "TypeScript",
    "Vite",
    "Node.js",
    "Express",
    "MongoDB",
    "Mongoose",
    "Tap Payments",
    "Vimeo API",
    "Tailwind CSS",
    "Zustand",
    "Framer Motion",
  ],
  image: "/uploads/aiqda-case-study/01-home.webp",
  screenshots: [
    "/uploads/aiqda-case-study/01-home.webp",
    "/uploads/aiqda-case-study/01b-home-packages.webp",
    "/uploads/aiqda-case-study/02-chapters.webp",
    "/uploads/aiqda-case-study/09-member-dashboard.webp",
    "/uploads/aiqda-case-study/10-member-progress.webp",
    "/uploads/aiqda-case-study/11-member-subscription.webp",
    "/uploads/aiqda-case-study/12-member-payments.webp",
    "/uploads/aiqda-case-study/13-member-chapter-detail.webp",
    "/uploads/aiqda-case-study/14-member-content-progress.webp",
    "/uploads/aiqda-case-study/03-consultations.webp",
    "/uploads/aiqda-case-study/04-creator-application.webp",
    "/uploads/aiqda-case-study/05-studio-application.webp",
    "/uploads/aiqda-case-study/06-admin-dashboard.webp",
    "/uploads/aiqda-case-study/07-admin-analytics.webp",
    "/uploads/aiqda-case-study/08-admin-finance.webp",
  ],
  serviceSlugs: ["custom-business-systems", "maintenance-performance-security"],
  liveUrl: "https://aiqda.pro",
  isFeatured: true,
  isPublished: true,
  sortOrder: 2,
  seoTitle: "Aiqda Learning Platform Case Study | Malek Fouda",
  seoDescription: "How Aiqda evolved from a learning MVP into a full-stack platform for subscriptions, payments, video learning, creator operations, finance, and analytics.",
};

export const TABLIYA_CASE_STUDY: InsertCaseStudy = {
  projectId: null,
  slug: "tabliya-shopify-middleware",
  title: "Tabliya — Shopify Order Middleware Built for Recovery",
  clientName: "Tabliya",
  industry: "Food Production / E-commerce Operations",
  summary: "A production-oriented integration service that turns Shopify order events into traceable Tabliya operations, with mapping controls, idempotency, retries, replay, and manual review built into the workflow.",
  context: "Tabliya uses Shopify for online ordering and a separate operational platform for products, orders, payment methods, invoices, and production workflows. The two systems use different identifiers and data contracts, so transferring an order involves more than forwarding a webhook payload.\n\nThe integration needed to cover the complete order lifecycle while giving operators a practical way to understand and recover from failures without creating duplicate records.",
  problem: "A direct Shopify-to-API call would leave several operational risks unresolved. Shopify can redeliver webhooks, events can arrive close together, and Tabliya requires its own product IDs and payment-method values. Addresses, delivery dates, discounts, payment state, updates, and cancellations also need deliberate transformation.\n\nIf a product was not mapped or the destination API became unavailable, the system needed to preserve the event, stop an incomplete order from being created, explain the failure, and support a controlled retry after the underlying issue was fixed.",
  role: "Full-stack integration architecture and implementation across Shopify webhooks, payload transformation, PostgreSQL persistence, background processing, the Tabliya API client, admin tooling, observability, and deployment configuration.",
  approach: "The service was designed as an auditable event pipeline. Shopify webhook signatures are verified against the raw request body before an event is accepted. Valid events are stored before processing, deduplicated by webhook and Shopify order identifiers, and handed to BullMQ for retryable background work, with an in-process fallback when Redis is unavailable.\n\nProduct and payment mappings are maintained separately from order logic. The transformer resolves those mappings, normalizes customer and address data, calculates delivery dates, translates payment state, and refuses to create a partial destination order when a line item is unknown.",
  solution: "The TypeScript and Express service handles Shopify order creation, updates, payments, fulfillment changes, edits, and cancellations. It creates or updates the corresponding Tabliya order, stores both request and response context, and preserves the relationship between the two systems. Cancellation first uses a configured or detected Tabliya status, verifies the result, and falls back safely when required. Optional invoice synchronization is isolated behind configuration.\n\nA protected admin console exposes product and payment mappings, webhook events, synchronization logs, settings, unresolved exceptions, manual replay, and reconciliation tools. Operators can correct a mapping and retry the original event instead of rebuilding an order by hand or losing the audit trail.",
  challenges: [
    "Preventing duplicate Tabliya orders when Shopify redelivers the same event or an operator initiates a replay.",
    "Translating Shopify products, variants, payment labels, addresses, delivery dates, discounts, and payment states into Tabliya's API contract.",
    "Applying cancellation safely despite multiple possible destination status endpoints and preserving the cancellation reason and timestamp.",
    "Keeping webhook acknowledgement fast while supporting retries, reconciliation, and useful failure visibility.",
    "Blocking incomplete orders when a mapping is missing, then making recovery straightforward for an operator.",
  ],
  results: [
    "Established an idempotent order pipeline with stored raw events and explicit synchronization state.",
    "Covered order creation, updates, payment and fulfillment changes, edits, cancellations, and optional invoice follow-up.",
    "Created operator-managed product and payment mappings instead of relying on fragile title matching.",
    "Added retry, replay, reconciliation, structured logs, and a manual-review queue for recoverable failures.",
    "Verified the local build, health endpoint, protected admin access, invalid-signature rejection, and unmapped-product review path against an isolated PostgreSQL database.",
  ],
  technologies: [
    "Shopify Webhooks",
    "Node.js",
    "TypeScript",
    "Express",
    "PostgreSQL",
    "Drizzle ORM",
    "Redis",
    "BullMQ",
    "Axios",
    "Zod",
    "Pino",
  ],
  image: "/uploads/tabliya-case-study/01-integration-settings.png",
  screenshots: [
    "/uploads/tabliya-case-study/01-integration-settings.png",
    "/uploads/tabliya-case-study/02-webhook-events.png",
  ],
  serviceSlugs: ["shopify-development", "custom-business-systems", "maintenance-performance-security"],
  liveUrl: "https://github.com/malekfouda2/Shopify-Orders-Middleware",
  isFeatured: true,
  isPublished: true,
  sortOrder: 3,
  seoTitle: "Tabliya Shopify Middleware Case Study | Malek Fouda",
  seoDescription: "How a Shopify middleware service synchronizes Tabliya orders with secure webhooks, mappings, idempotency, retries, replay, logs, and manual review.",
};
