// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-redesign/BoldDeveloper.tsx": () => import("../components/mockups/portfolio-redesign/BoldDeveloper.tsx"),
  "./components/mockups/portfolio-redesign/Editorial.tsx": () => import("../components/mockups/portfolio-redesign/Editorial.tsx"),
  "./components/mockups/portfolio-redesign/PremiumDark.tsx": () => import("../components/mockups/portfolio-redesign/PremiumDark.tsx")
};
